Tilina-FMS/apps/students/urls.py
from django.urls import path

from .views import (
    DownloadCSVViewdownloadcsv,
    StudentBulkUploadView,
    StudentCreateView,
    StudentDeleteView,
    StudentDetailView,
    StudentListView,
    StudentUpdateView,
)

urlpatterns = [
    path("list", StudentListView.as_view(), name="student-list"),
    path("<int:pk>/", StudentDetailView.as_view(), name="student-detail"),
    path("create/", StudentCreateView.as_view(), name="student-create"),
    path("<int:pk>/update/", StudentUpdateView.as_view(), name="student-update"),
    path("delete/<int:pk>/", StudentDeleteView.as_view(), name="student-delete"),
    path("upload/", StudentBulkUploadView.as_view(), name="student-upload"),
    path("download-csv/", DownloadCSVViewdownloadcsv.as_view(), name="download-csv"),
]

Tilina-FMS/school_app/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),  # ULRs to the ADMIN App
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("apps.corecode.urls")),
    path("student/", include("apps.students.urls")),
    # path("staff/", include("apps.staffs.urls")),
    path("finance/", include("apps.finance.urls")),
    path("result/", include("apps.result.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tilina-FMS/apps/students/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone

from apps.corecode.models import StudentClass


class Student(models.Model):
    STATUS_CHOICES = [("active", "Active"), ("inactive", "Inactive")]

    GENDER_CHOICES = [("male", "Male"), ("female", "Female")]

    current_status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="active"
    )
    # registration_number = models.CharField(max_length=200, unique=True)
    last_name = models.CharField(max_length=60)
    first_name = models.CharField(max_length=60)
    middle_name = models.CharField(max_length=60, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default="male")
    date_of_birth = models.DateField(default=timezone.now)
    current_class = models.ForeignKey(
        StudentClass, on_delete=models.SET_NULL, blank=True, null=True
    )
    date_of_admission = models.DateField(default=timezone.now)
    created_at = models.DateTimeField(default=timezone.now)

    mobile_num_regex = RegexValidator(
        regex="^[0-9]{10,15}$", message="Entered mobile number isn't in a right format!"
    )
    parent_mobile_number = models.CharField(
        validators=[mobile_num_regex], max_length=13, blank=True
    )
    village = models.CharField(max_length=60)
    traditional_authority = models.CharField(max_length=60)
    district = models.CharField(max_length=60)
    others = models.TextField(blank=True)
    address = models.TextField(blank=True, verbose_name="Residential Address")
    denomination = models.CharField(max_length=60)
    allergies = models.TextField(blank=True)
    medical_doctor = models.CharField(max_length=60)



    passport = models.ImageField(blank=True, upload_to="students/passports/")

    class Meta:
        ordering = ["last_name", "first_name", "middle_name"]

    def __str__(self):
        return f"{self.last_name} {self.first_name} {self.middle_name}"

    def get_absolute_url(self):
        return reverse("student-detail", kwargs={"pk": self.pk})


class StudentBulkUpload(models.Model):
    date_uploaded = models.DateTimeField(auto_now=True)
    csv_file = models.FileField(upload_to="students/bulkupload/")

Tilina-FMS/apps/students/views.py
import csv

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import widgets
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from apps.finance.models import Invoice

from .models import Student, StudentBulkUpload


class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    context_object_name = 'students'
    template_name = "students/student_list.html"


class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Student
    template_name = "students/student_detail.html"

    def get_context_data(self, **kwargs):
        context = super(StudentDetailView, self).get_context_data(**kwargs)
        context["payments"] = Invoice.objects.filter(student=self.object)
        return context


class StudentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Student
    fields = "__all__"
    success_message = "New student successfully added."

    def get_form(self):
        """add date picker in forms"""
        form = super(StudentCreateView, self).get_form()
        form.fields["date_of_birth"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 2})
        form.fields["others"].widget = widgets.Textarea(attrs={"rows": 2})
        return form


class StudentUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Student
    fields = "__all__"
    success_message = "Record successfully updated."

    def get_form(self):
        """add date picker in forms"""
        form = super(StudentUpdateView, self).get_form()
        form.fields["date_of_birth"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["date_of_admission"].widget = widgets.DateInput(
            attrs={"type": "date"}
        )
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 2})
        form.fields["others"].widget = widgets.Textarea(attrs={"rows": 2})
        # form.fields['passport'].widget = widgets.FileInput()
        return form


class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy("student-list")


class StudentBulkUploadView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = StudentBulkUpload
    template_name = "students/students_upload.html"
    fields = ["csv_file"]
    success_url = "/student/list"
    success_message = "Successfully uploaded students"


class DownloadCSVViewdownloadcsv(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type="text/csv")
        response["Content-Disposition"] = 'attachment; filename="student_template.csv"'

        writer = csv.writer(response)
        writer.writerow(
            [
                "registration_number",
                "last_name",
                "first_name",
                "middle_names",
                "gender",
                "parent_number",
                "address",
                "current_class",
            ]
        )

        return response

Tilina-FMS/apps/students/templates/students/student_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <p>All contents attached to this student will be deleted</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

Tilina-FMS/apps/students/templates/students/student_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <a href="#" class="btn btn-tool">Print</a>
    <a href="{% url 'student-update' object.id %}" class="btn btn-tool">
      <i class="fas fa-edit"></i>
    </a>
    <a href="{% url 'student-delete' object.id %}" class="btn btn-tool">
      <i class="fas fa-times"></i>
    </a>
  </div>
</div>
{% endblock content-header %}

{% block content %}
    <div class="row mb-4">
      <div class="col-sm-4">
        <div class="row mb-2">

          {% if object.passport %}
            <img
              src="{{ object.passport.url }}"
              class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% else %}
            <img
              src="{% static 'dist/img/avatar.png' %}"
              class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% endif %}


          <div class="float-right">
            <h4>{{ object.last_name }} </h4>
            <h4>{{ object.first_name }} </h4>
            <h4>{{ object.middle_name }} </h4>
            <h4>{{ object.registration_number }} </h4>
          </div>
        </div>
        <h5>{{ object.current_class }} </h5>
        <h5>{{ object.get_gender_display }} | {{ object.get_current_status_display }}</h5>

      </div>
      <div class="col-sm-8">
        <div>
          <div class="form-group border-bottom row">
            <label class="col">
              Date of Birth
            </label>
            <div class="col">
              {{ object.date_of_birth }}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              Parent Mobile Number
            </label>
            <div class="col">
              {{ object.parent_mobile_number}}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              Address
            </label>
            <div class="col">
              {{ object.address }}
            </div>
          </div>
          <div class="form-group border-bottom row">
            <label class="col">
              Comments
            </label>
            <div class="col">
              {{ object.others }}
            </div>
          </div>

        </div>

      </div>
    </div>

    <h4>Invoice/Payment History</h4>
    {% if payments %}
      <table class="table table-sm table-bordered table-hover">
        <thead class="thead-light">
          <tr>
            <th>For</th>
            <th>Amount Payable</th>
            <th>Amount Paid</th>
            <th>balance</th>
          </tr>
        </thead>
        <tbody>
          {% for payment in payments %}
            <tr class='clickable-row' data-href="{% url 'invoice-detail' payment.id %}">
              <td>{{payment.session}} - {{payment.term}} - {{ payment.class_for}}</td>
              <td>{{payment.total_amount_payable}}</td>
              <td>{{payment.total_amount_paid}}</td>
              <td>{{payment.balance}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
        <p>There are no payment history for {{object}}</p>
    {% endif %}




{% endblock content %}

Tilina-FMS/apps/students/templates/students/student_form.html
{% extends 'base.html' %}


{% block title %}

  {% if object %}
    Update {{ object }}
  {% else %}
    Add new student
  {% endif %}

{% endblock title %}


{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  {% include 'corecode/form_snippet.html' %}

  {% if object %}
    <input type="submit" class="btn btn-primary" value="Update Record">
  {% else %}
    <input type="submit" class="btn btn-primary" value="Add new student">
  {% endif %}
</form>


{% endblock content %}

Tilina-FMS/apps/students/templates/students/student_list.html
{% extends 'base.html' %}

{% block title %}Students{% endblock title %}

{% block breadcrumb %}
<a class="btn btn-primary" href="{% url 'student-create' %}"><i
    class="fas fa-plus"></i> New student</a>
<a class="btn btn-primary" href="{% url 'student-upload' %}"><i
    class="fas fa-upload"></i> Upload students</a>
{% endblock breadcrumb %}

{% block content %}
  <div class="table-responsive">
    <table id="studenttable" class="table table-bordered table-hover" data-page-length='100'>
      <thead class="thead-light">
        <tr>
          <th>S/N</th>
          <th>Fullname</th>
          <th>Current Class</th>
          <th>Gender</th>
          <th>Mobile Phone Number</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>

        {% for student in students %}
          <tr class='clickable-row' data-href="{% url 'student-detail' student.id %}">
            <td>{{ forloop.counter}}</td>
            <td>{{ student.last_name}} {{student.first_name }} {{student.middle_name }}</td>
            <td>{{ student.current_class}}</td>
            <td>{{ student.get_gender_display}}</td>
            <td>{{ student.parent_mobile_number}}</td>
            <td>{{ student.get_current_status_display}}</td>
          </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
{% endblock content %}


{% block morejs %}
<script>
  $('#studenttable').DataTable({
  });
</script>

{% endblock morejs %}

Tilina-FMS/apps/students/templates/students/students_upload.html
{% extends 'base.html' %}


{% block title %}
  Upload Bulk Students from file
{% endblock title %}


{% block content %}

  <div class="col alert alert-info">
    <h5>Instruction</h5>
    <p>Please <a href="{% url 'download-csv' %}">download the CSV file attached here</a>. Fill in the sheet and upload the same file back to this page. DO NOT EDIT THE FIRST ROW</p>
  </div>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'corecode/form_snippet.html' %}

    <input type="submit" class="btn btn-success" value="Submit">
  </form>

{% endblock content %}